name: Test Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/build-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: Build all platforms
        run: make build-all

      - name: Test build success
        run: |
          ls -la bin/
          echo "Build completed successfully!"
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gateshift-dev-binaries
          path: bin/
          retention-days: 3 